GET http://localhost:8000/todos HTTP/1.1

###

POST http://localhost:8000/todo/new
Content-Type: application/json

{
	"text": "Pick up boat"
}

###

DELETE http://localhost:8000/todo/delete/64944592962c8b90fa0ca43a

###

GET http://localhost:8000/todo/complete/64944592962c8b90fa0ca43a

###

PUT http://localhost:8000/todo/update/64944592962c8b90fa0ca43a
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}